//gm82 fields begin
spike_down=sprCharmSpikeD
spike_right=sprCharmSpikeR
spike_left=sprCharmSpikeL
spike_up=sprCharmSpikeU
mini_spike_down=sprCharmMSpikeD
mini_spike_right=sprCharmMSpikeR
mini_spike_left=sprCharmMSpikeL
mini_spike_up=sprCharmMSpikeU
fruit=sprCherryPink
//gm82 fields end
