//gm82 fields begin
spike_down=sprPlainSpikeDown
spike_right=sprPlainSpikeRight
spike_left=sprPlainSpikeLeft
spike_up=sprPlainSpikeUp
mini_spike_down=sprPlainSpikeD
mini_spike_right=sprPlainSpikeR
mini_spike_left=sprPlainSpikeL
mini_spike_up=sprPlainSpikeUp
fruit=sprMirrorCherry2
//gm82 fields end
